const LOGIN_USER = 'LOGIN_USER'
const REMOVE_USER = 'REMOVE_USER'
const COLLAPSED = 'COLLAPSED'
const OVERVIEW_ALGORITHM = 'OVERVIEW_ALGORITHM'
const ALGO_INFORMATION = 'ALGO_INFORMATION'
const ALGO_PRINCIPLE = 'ALGO_PRINCIPLE'
const WATCH_LIST = 'WATCH_LIST'
const STRATEGY_EQUITY = 'STRATEGY_EQUITY'
const CAPITAL_GROWTH = 'CAPITAL_GROWTH'
const DRAWDOWN_TABLE = 'DRAWDOWN_TABLE'
const SHOW_ALGO_INFO_PAGE = 'SHOW_ALGO_INFO_PAGE'
const HISTORICAL_GRAPH = 'HISTORICAL_GRAPH'
const DRAWDOWN = 'DRAWDOWN'
const ALGO_MART_GRAPH = 'ALGO_MART_GRAPH'
const PORTFOLIO_PERFORMANCE_GRAPH = 'PORTFOLIO_PERFORMANCE_GRAPH'
const PORTFOLIO_EFFICIENCY = 'PORTFOLIO_EFFICIENCY'
const OVERVIEW_TABLE = 'OVERVIEW_TABLE'
const ROLLING_RETURN_TABLE = 'ROLLING_RETURN_TABLE'
const TRADE_LOG_TABLE = 'TRADE_LOG_TABLE'
const RELATED_CONST_STOCK = 'RELATED_CONST_STOCK'
const HISTORICAL_RETURN_TABLE = 'HISTORICAL_RETURN_TABLE'
const ROLLING_RETURN_GRAPH = 'ROLLING_RETURN_GRAPH'
const INFORMATION_TOP_TABLE = 'INFORMATION_TOP_TABLE'
const ALOG_TRADING_CARDS = 'ALOG_TRADING_CARDS'
const ALL_USERS = 'ALL_USERS'

export {
    LOGIN_USER,
    REMOVE_USER,
    COLLAPSED,
    OVERVIEW_ALGORITHM,
    ALGO_INFORMATION,
    ALGO_PRINCIPLE,
    WATCH_LIST,
    STRATEGY_EQUITY,
    CAPITAL_GROWTH,
    DRAWDOWN_TABLE,
    SHOW_ALGO_INFO_PAGE,
    HISTORICAL_GRAPH,
    DRAWDOWN,
    ALGO_MART_GRAPH,
    PORTFOLIO_PERFORMANCE_GRAPH,
    PORTFOLIO_EFFICIENCY,
    OVERVIEW_TABLE,
    ROLLING_RETURN_TABLE,
    TRADE_LOG_TABLE,
    RELATED_CONST_STOCK,
    HISTORICAL_RETURN_TABLE,
    ROLLING_RETURN_GRAPH,
    INFORMATION_TOP_TABLE,
    ALOG_TRADING_CARDS,
    ALL_USERS
}
